site_name: VoxelGamesLib Documentation
site_description: Developer and user documentation for VoxelGamesLib v2
site_author: VoxelGamesLib
site_url: voxelgameslib.com

repo_name: 'VoxelGamesLib'
repo_url: 'https://github.com/VoxelGamesLib/VoxelGamesLibv2'

copyright: 'Copyright &copy; 2016 - 2018 VoxelGamesLib, MiniDigger and Contributors'

theme:
  name: 'material'
  palette:
    primary: 'amber'
    accent: 'orange'
  logo: 'images/logo.svg'
  feature:
    tabs: true

edit_uri: 'blob/master/docs/'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/VoxelGamesLib'
    - type: 'twitter'
      link: 'https://twitter.com/xMiniDiggerx'
google_analytics:
- 'UA-38006759-6'
- 'auto'
pages:
- Introduction: index.md
- General:
  - Doctrine: general/doctrine.md
  - Getting started: general/getting-started.md
  - Terms: general/terms.md
- Components:
  - General: components/general.md
  - Features: components/features.md
  - Phases: components/phases.md
  - Games: components/games.md
- Mapper Area:
  - Introduction: maps/introduction.md
  - How to create a map: maps/how-to-create-a-map.md
- Designer Area:
  - Index: designer-area/index.md
- Developer Area:
  - How to write an addon: developer-area/how-to-write-an-addon.md
  - How to write a feature: developer-area/how-to-write-a-feature.md
  - How to write a phase: developer-area/how-to-write-a-phase.md
  - How to write a game: developer-area/how-to-write-a-game.md
  - How to use the i18n API: developer-area/how-to-use-the-i18n-api.md
  - Introduction to Guice: developer-area/introduction-to-guice.md
  - APIs: 
    - Scoreboard API: developer-area/apis/scoreboard.md
    - Kit API: developer-area/apis/kit.md
    - Sign API: developer-area/apis/sign.md
    - Elo API: developer-area/apis/elo.md
    - Command API: developer-area/apis/command.md
    - Ability API: developer-area/apis/ability.md
- Contributor Area:
  - General: contributor-area/general.md
  - Contributors: contributor-area/contributors.md
  - Contribute Code: contributor-area/contribute-code.md
  - Contribute Maps: contributor-area/contribute-maps.md
  - Contribute Translations: contributor-area/contribute-translations.md
  - Create bug reports or feature requests: contributor-area/create-bug-reports-or-feature-requests.md
  - Contributor's Corner: contributor-area/contributors-corner.md
- Test:
  - Test: test/testpage.md

markdown_extensions:
  # notes quotes etc
  - admonition
  # code highlights
  - codehilite(linenums=true)
  # footnotes
  - footnotes
  # table of contents, permalinks
  - toc(permalink=true)
  # bunch of random crap
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
